language: python
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10.2
python:
  - "3.7"
install:
    - pip install cython
    - python setup.py build_ext -i
    - python setup.py install
script:
    - pytest
