# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.openPreferencesButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPreferencesButton.sizePolicy().hasHeightForWidth())
        self.openPreferencesButton.setSizePolicy(sizePolicy)
        self.openPreferencesButton.setObjectName("openPreferencesButton")
        self.gridLayout.addWidget(self.openPreferencesButton, 0, 5, 1, 1)
        self.alphaSliderLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaSliderLabel.sizePolicy().hasHeightForWidth())
        self.alphaSliderLabel.setSizePolicy(sizePolicy)
        self.alphaSliderLabel.setObjectName("alphaSliderLabel")
        self.gridLayout.addWidget(self.alphaSliderLabel, 0, 2, 1, 1)
        self.alphaSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaSlider.sizePolicy().hasHeightForWidth())
        self.alphaSlider.setSizePolicy(sizePolicy)
        self.alphaSlider.setMinimum(1)
        self.alphaSlider.setMaximum(100)
        self.alphaSlider.setSliderPosition(50)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName("alphaSlider")
        self.gridLayout.addWidget(self.alphaSlider, 0, 3, 1, 1)
        self.zoomSliderLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSliderLabel.sizePolicy().hasHeightForWidth())
        self.zoomSliderLabel.setSizePolicy(sizePolicy)
        self.zoomSliderLabel.setObjectName("zoomSliderLabel")
        self.gridLayout.addWidget(self.zoomSliderLabel, 0, 0, 1, 1)
        self.mergeSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeSlider.sizePolicy().hasHeightForWidth())
        self.mergeSlider.setSizePolicy(sizePolicy)
        self.mergeSlider.setMinimum(1)
        self.mergeSlider.setMaximum(10)
        self.mergeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mergeSlider.setInvertedAppearance(False)
        self.mergeSlider.setInvertedControls(False)
        self.mergeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mergeSlider.setTickInterval(1)
        self.mergeSlider.setObjectName("mergeSlider")
        self.gridLayout.addWidget(self.mergeSlider, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 624, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 6)
        self.statisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.statisticsButton.setObjectName("statisticsButton")
        self.gridLayout.addWidget(self.statisticsButton, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuVMD = QtWidgets.QMenu(self.menubar)
        self.menuVMD.setObjectName("menuVMD")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRun_VMD_contact_search = QtWidgets.QAction(MainWindow)
        self.actionRun_VMD_contact_search.setObjectName("actionRun_VMD_contact_search")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menuVMD.addAction(self.actionRun_VMD_contact_search)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuVMD.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openPreferencesButton.setText(_translate("MainWindow", "Preferences"))
        self.alphaSliderLabel.setText(_translate("MainWindow", "Alpha:"))
        self.zoomSliderLabel.setText(_translate("MainWindow", "Zoom:"))
        self.statisticsButton.setText(_translate("MainWindow", "Statistics"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuVMD.setTitle(_translate("MainWindow", "VMD"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionRun_VMD_contact_search.setText(_translate("MainWindow", "Run VMD contact search"))

