# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsWindowWidget(object):
    def setupUi(self, settingsWindowWidget):
        settingsWindowWidget.setObjectName("settingsWindowWidget")
        settingsWindowWidget.resize(597, 699)
        self.filterTab = QtWidgets.QWidget()
        self.filterTab.setObjectName("filterTab")
        self.filterWidget = QtWidgets.QWidget(self.filterTab)
        self.filterWidget.setGeometry(QtCore.QRect(-1, -1, 591, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWidget.sizePolicy().hasHeightForWidth())
        self.filterWidget.setSizePolicy(sizePolicy)
        self.filterWidget.setObjectName("filterWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.filterWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.filterRangeCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.filterRangeCheckbox.setObjectName("filterRangeCheckbox")
        self.gridLayout.addWidget(self.filterRangeCheckbox, 0, 3, 1, 1)
        self.residBNameField = QtWidgets.QLineEdit(self.filterWidget)
        self.residBNameField.setObjectName("residBNameField")
        self.gridLayout.addWidget(self.residBNameField, 9, 4, 1, 1)
        self.residANameField = QtWidgets.QLineEdit(self.filterWidget)
        self.residANameField.setObjectName("residANameField")
        self.gridLayout.addWidget(self.residANameField, 9, 2, 1, 1)
        self.residBRangeField = QtWidgets.QLineEdit(self.filterWidget)
        self.residBRangeField.setObjectName("residBRangeField")
        self.gridLayout.addWidget(self.residBRangeField, 8, 4, 1, 1)
        self.upperRangeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperRangeField.sizePolicy().hasHeightForWidth())
        self.upperRangeField.setSizePolicy(sizePolicy)
        self.upperRangeField.setObjectName("upperRangeField")
        self.gridLayout.addWidget(self.upperRangeField, 1, 2, 1, 1)
        self.sortingLabel = QtWidgets.QLabel(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortingLabel.sizePolicy().hasHeightForWidth())
        self.sortingLabel.setSizePolicy(sizePolicy)
        self.sortingLabel.setObjectName("sortingLabel")
        self.gridLayout.addWidget(self.sortingLabel, 6, 0, 1, 1)
        self.activeScoreCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeScoreCheckbox.setObjectName("activeScoreCheckbox")
        self.gridLayout.addWidget(self.activeScoreCheckbox, 5, 3, 1, 1)
        self.residARangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.residARangeLabel.setObjectName("residARangeLabel")
        self.gridLayout.addWidget(self.residARangeLabel, 8, 1, 1, 1)
        self.totalTimeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeField.sizePolicy().hasHeightForWidth())
        self.totalTimeField.setSizePolicy(sizePolicy)
        self.totalTimeField.setObjectName("totalTimeField")
        self.gridLayout.addWidget(self.totalTimeField, 4, 2, 1, 1)
        self.residANameLabel = QtWidgets.QLabel(self.filterWidget)
        self.residANameLabel.setObjectName("residANameLabel")
        self.gridLayout.addWidget(self.residANameLabel, 9, 1, 1, 1)
        self.toRangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.toRangeLabel.setObjectName("toRangeLabel")
        self.gridLayout.addWidget(self.toRangeLabel, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.filterWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.filterWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 5)
        self.fromRangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.fromRangeLabel.setObjectName("fromRangeLabel")
        self.gridLayout.addWidget(self.fromRangeLabel, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.filterWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 11, 0, 1, 5)
        self.rangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout.addWidget(self.rangeLabel, 0, 0, 1, 1)
        self.residBNameLabel = QtWidgets.QLabel(self.filterWidget)
        self.residBNameLabel.setObjectName("residBNameLabel")
        self.gridLayout.addWidget(self.residBNameLabel, 9, 3, 1, 1)
        self.lowerRangeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerRangeField.sizePolicy().hasHeightForWidth())
        self.lowerRangeField.setSizePolicy(sizePolicy)
        self.lowerRangeField.setObjectName("lowerRangeField")
        self.gridLayout.addWidget(self.lowerRangeField, 0, 2, 1, 1)
        self.activeTotalTimeCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeTotalTimeCheckbox.setObjectName("activeTotalTimeCheckbox")
        self.gridLayout.addWidget(self.activeTotalTimeCheckbox, 4, 3, 1, 1)
        self.compareScoreDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.compareScoreDropdown.setObjectName("compareScoreDropdown")
        self.compareScoreDropdown.addItem("")
        self.compareScoreDropdown.addItem("")
        self.gridLayout.addWidget(self.compareScoreDropdown, 5, 1, 1, 1)
        self.totalTimeLabel = QtWidgets.QLabel(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeLabel.sizePolicy().hasHeightForWidth())
        self.totalTimeLabel.setSizePolicy(sizePolicy)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.gridLayout.addWidget(self.totalTimeLabel, 4, 0, 1, 1)
        self.compareTotalTimeDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.compareTotalTimeDropdown.setObjectName("compareTotalTimeDropdown")
        self.compareTotalTimeDropdown.addItem("")
        self.compareTotalTimeDropdown.addItem("")
        self.gridLayout.addWidget(self.compareTotalTimeDropdown, 4, 1, 1, 1)
        self.meanDropdown = QtWidgets.QComboBox(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanDropdown.sizePolicy().hasHeightForWidth())
        self.meanDropdown.setSizePolicy(sizePolicy)
        self.meanDropdown.setObjectName("meanDropdown")
        self.meanDropdown.addItem("")
        self.meanDropdown.addItem("")
        self.gridLayout.addWidget(self.meanDropdown, 5, 0, 1, 1)
        self.sortingKeyDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.sortingKeyDropdown.setObjectName("sortingKeyDropdown")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.gridLayout.addWidget(self.sortingKeyDropdown, 6, 1, 1, 1)
        self.scoreField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreField.sizePolicy().hasHeightForWidth())
        self.scoreField.setSizePolicy(sizePolicy)
        self.scoreField.setObjectName("scoreField")
        self.gridLayout.addWidget(self.scoreField, 5, 2, 1, 1)
        self.sortingOrderDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.sortingOrderDropdown.setObjectName("sortingOrderDropdown")
        self.sortingOrderDropdown.addItem("")
        self.sortingOrderDropdown.addItem("")
        self.gridLayout.addWidget(self.sortingOrderDropdown, 6, 2, 1, 1)
        self.residARangeField = QtWidgets.QLineEdit(self.filterWidget)
        self.residARangeField.setObjectName("residARangeField")
        self.gridLayout.addWidget(self.residARangeField, 8, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 4, 1, 1)
        self.residuesLabel = QtWidgets.QLabel(self.filterWidget)
        self.residuesLabel.setObjectName("residuesLabel")
        self.gridLayout.addWidget(self.residuesLabel, 8, 0, 1, 1)
        self.functionGroupBox = QtWidgets.QGroupBox(self.filterWidget)
        self.functionGroupBox.setObjectName("functionGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.functionGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weightFunctionWidget = QtWidgets.QWidget(self.functionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightFunctionWidget.sizePolicy().hasHeightForWidth())
        self.weightFunctionWidget.setSizePolicy(sizePolicy)
        self.weightFunctionWidget.setObjectName("weightFunctionWidget")
        self.functionGridLayout = QtWidgets.QGridLayout(self.weightFunctionWidget)
        self.functionGridLayout.setObjectName("functionGridLayout")
        self.sigmoidRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.sigmoidRadioButton.setChecked(True)
        self.sigmoidRadioButton.setObjectName("sigmoidRadioButton")
        self.functionGridLayout.addWidget(self.sigmoidRadioButton, 0, 0, 1, 1)
        self.linRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.linRadioButton.setObjectName("linRadioButton")
        self.functionGridLayout.addWidget(self.linRadioButton, 0, 2, 1, 1)
        self.rectRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.rectRadioButton.setObjectName("rectRadioButton")
        self.functionGridLayout.addWidget(self.rectRadioButton, 0, 1, 1, 1)
        self.previewButton = QtWidgets.QPushButton(self.weightFunctionWidget)
        self.previewButton.setObjectName("previewButton")
        self.functionGridLayout.addWidget(self.previewButton, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.weightFunctionWidget)
        self.gridLayout.addWidget(self.functionGroupBox, 12, 0, 3, 4)
        self.applyFilterButton = QtWidgets.QPushButton(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyFilterButton.sizePolicy().hasHeightForWidth())
        self.applyFilterButton.setSizePolicy(sizePolicy)
        self.applyFilterButton.setObjectName("applyFilterButton")
        self.gridLayout.addWidget(self.applyFilterButton, 14, 4, 1, 1)
        self.functionActiveCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.functionActiveCheckbox.setObjectName("functionActiveCheckbox")
        self.gridLayout.addWidget(self.functionActiveCheckbox, 12, 4, 1, 1)
        self.residBRangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.residBRangeLabel.setObjectName("residBRangeLabel")
        self.gridLayout.addWidget(self.residBRangeLabel, 8, 3, 1, 1)
        self.activeSortingBox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeSortingBox.setObjectName("activeSortingBox")
        self.gridLayout.addWidget(self.activeSortingBox, 6, 3, 1, 1)
        self.filterWidget.raise_()
        self.applyFilterButton.raise_()
        settingsWindowWidget.addTab(self.filterTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsWidget = QtWidgets.QWidget(self.settingsTab)
        self.settingsWidget.setGeometry(QtCore.QRect(-1, -1, 581, 431))
        self.settingsWidget.setObjectName("settingsWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingsWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.thresholdLabel = QtWidgets.QLabel(self.settingsWidget)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.gridLayout_2.addWidget(self.thresholdLabel, 1, 0, 1, 1)
        self.thresholdField = QtWidgets.QLineEdit(self.settingsWidget)
        self.thresholdField.setClearButtonEnabled(True)
        self.thresholdField.setObjectName("thresholdField")
        self.gridLayout_2.addWidget(self.thresholdField, 1, 1, 1, 1)
        self.applySettingsButton = QtWidgets.QPushButton(self.settingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applySettingsButton.sizePolicy().hasHeightForWidth())
        self.applySettingsButton.setSizePolicy(sizePolicy)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.gridLayout_2.addWidget(self.applySettingsButton, 4, 2, 1, 1)
        self.nsPerFrameField = QtWidgets.QLineEdit(self.settingsWidget)
        self.nsPerFrameField.setClearButtonEnabled(True)
        self.nsPerFrameField.setObjectName("nsPerFrameField")
        self.gridLayout_2.addWidget(self.nsPerFrameField, 0, 1, 1, 1)
        self.nsPerFrameLabel = QtWidgets.QLabel(self.settingsWidget)
        self.nsPerFrameLabel.setObjectName("nsPerFrameLabel")
        self.gridLayout_2.addWidget(self.nsPerFrameLabel, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 2)
        settingsWindowWidget.addTab(self.settingsTab, "")

        self.retranslateUi(settingsWindowWidget)
        settingsWindowWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settingsWindowWidget)

    def retranslateUi(self, settingsWindowWidget):
        _translate = QtCore.QCoreApplication.translate
        settingsWindowWidget.setWindowTitle(_translate("settingsWindowWidget", "Preferences"))
        self.filterRangeCheckbox.setText(_translate("settingsWindowWidget", "filter range"))
        self.residBNameField.setText(_translate("settingsWindowWidget", "all"))
        self.residANameField.setText(_translate("settingsWindowWidget", "all"))
        self.residBRangeField.setText(_translate("settingsWindowWidget", "all"))
        self.upperRangeField.setText(_translate("settingsWindowWidget", "end"))
        self.sortingLabel.setText(_translate("settingsWindowWidget", "sorting:"))
        self.activeScoreCheckbox.setText(_translate("settingsWindowWidget", "active"))
        self.residARangeLabel.setText(_translate("settingsWindowWidget", "range A:"))
        self.totalTimeField.setText(_translate("settingsWindowWidget", "0"))
        self.residANameLabel.setText(_translate("settingsWindowWidget", "names A:"))
        self.toRangeLabel.setText(_translate("settingsWindowWidget", "to:"))
        self.fromRangeLabel.setText(_translate("settingsWindowWidget", "from:"))
        self.rangeLabel.setText(_translate("settingsWindowWidget", "Display range:"))
        self.residBNameLabel.setText(_translate("settingsWindowWidget", "names B:"))
        self.lowerRangeField.setText(_translate("settingsWindowWidget", "1"))
        self.activeTotalTimeCheckbox.setText(_translate("settingsWindowWidget", "active"))
        self.compareScoreDropdown.setCurrentText(_translate("settingsWindowWidget", "greater"))
        self.compareScoreDropdown.setItemText(0, _translate("settingsWindowWidget", "greater"))
        self.compareScoreDropdown.setItemText(1, _translate("settingsWindowWidget", "smaller"))
        self.totalTimeLabel.setText(_translate("settingsWindowWidget", "total time:"))
        self.compareTotalTimeDropdown.setCurrentText(_translate("settingsWindowWidget", "greater"))
        self.compareTotalTimeDropdown.setItemText(0, _translate("settingsWindowWidget", "greater"))
        self.compareTotalTimeDropdown.setItemText(1, _translate("settingsWindowWidget", "smaller"))
        self.meanDropdown.setItemText(0, _translate("settingsWindowWidget", "mean"))
        self.meanDropdown.setItemText(1, _translate("settingsWindowWidget", "median"))
        self.sortingKeyDropdown.setItemText(0, _translate("settingsWindowWidget", "mean"))
        self.sortingKeyDropdown.setItemText(1, _translate("settingsWindowWidget", "median"))
        self.sortingKeyDropdown.setItemText(2, _translate("settingsWindowWidget", "bb/sc type"))
        self.sortingKeyDropdown.setItemText(3, _translate("settingsWindowWidget", "contact type"))
        self.sortingKeyDropdown.setItemText(4, _translate("settingsWindowWidget", "total time"))
        self.sortingKeyDropdown.setItemText(5, _translate("settingsWindowWidget", "resid A"))
        self.sortingKeyDropdown.setItemText(6, _translate("settingsWindowWidget", "resid B"))
        self.scoreField.setText(_translate("settingsWindowWidget", "0"))
        self.sortingOrderDropdown.setItemText(0, _translate("settingsWindowWidget", "asc"))
        self.sortingOrderDropdown.setItemText(1, _translate("settingsWindowWidget", "desc"))
        self.residARangeField.setText(_translate("settingsWindowWidget", "all"))
        self.residuesLabel.setText(_translate("settingsWindowWidget", "residues:"))
        self.functionGroupBox.setTitle(_translate("settingsWindowWidget", "Frame weight functions"))
        self.sigmoidRadioButton.setText(_translate("settingsWindowWidget", "sigmoid"))
        self.linRadioButton.setText(_translate("settingsWindowWidget", "linear"))
        self.rectRadioButton.setText(_translate("settingsWindowWidget", "rectangle"))
        self.previewButton.setText(_translate("settingsWindowWidget", "Preview"))
        self.applyFilterButton.setText(_translate("settingsWindowWidget", "Apply"))
        self.functionActiveCheckbox.setText(_translate("settingsWindowWidget", "weight active"))
        self.residBRangeLabel.setText(_translate("settingsWindowWidget", "range B:"))
        self.activeSortingBox.setText(_translate("settingsWindowWidget", "active"))
        settingsWindowWidget.setTabText(settingsWindowWidget.indexOf(self.filterTab), _translate("settingsWindowWidget", "Filters"))
        self.thresholdLabel.setText(_translate("settingsWindowWidget", "Threshold:"))
        self.thresholdField.setText(_translate("settingsWindowWidget", "0.0"))
        self.applySettingsButton.setText(_translate("settingsWindowWidget", "Apply"))
        self.nsPerFrameField.setText(_translate("settingsWindowWidget", "1.0"))
        self.nsPerFrameLabel.setText(_translate("settingsWindowWidget", "Nanoseconds per frame:"))
        settingsWindowWidget.setTabText(settingsWindowWidget.indexOf(self.settingsTab), _translate("settingsWindowWidget", "Settings"))

