# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsWindowWidget(object):
    def setupUi(self, settingsWindowWidget):
        settingsWindowWidget.setObjectName("settingsWindowWidget")
        settingsWindowWidget.resize(597, 699)
        self.filterTab = QtWidgets.QWidget()
        self.filterTab.setObjectName("filterTab")
        self.filterWidget = QtWidgets.QWidget(self.filterTab)
        self.filterWidget.setGeometry(QtCore.QRect(-1, -1, 591, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWidget.sizePolicy().hasHeightForWidth())
        self.filterWidget.setSizePolicy(sizePolicy)
        self.filterWidget.setObjectName("filterWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.filterWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.functionActiveCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.functionActiveCheckbox.setObjectName("functionActiveCheckbox")
        self.gridLayout.addWidget(self.functionActiveCheckbox, 13, 4, 1, 1)
        self.functionGroupBox = QtWidgets.QGroupBox(self.filterWidget)
        self.functionGroupBox.setObjectName("functionGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.functionGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weightFunctionWidget = QtWidgets.QWidget(self.functionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightFunctionWidget.sizePolicy().hasHeightForWidth())
        self.weightFunctionWidget.setSizePolicy(sizePolicy)
        self.weightFunctionWidget.setObjectName("weightFunctionWidget")
        self.functionGridLayout = QtWidgets.QGridLayout(self.weightFunctionWidget)
        self.functionGridLayout.setObjectName("functionGridLayout")
        self.sigmoidRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.sigmoidRadioButton.setChecked(True)
        self.sigmoidRadioButton.setObjectName("sigmoidRadioButton")
        self.functionGridLayout.addWidget(self.sigmoidRadioButton, 0, 0, 1, 1)
        self.linRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.linRadioButton.setObjectName("linRadioButton")
        self.functionGridLayout.addWidget(self.linRadioButton, 0, 2, 1, 1)
        self.rectRadioButton = QtWidgets.QRadioButton(self.weightFunctionWidget)
        self.rectRadioButton.setObjectName("rectRadioButton")
        self.functionGridLayout.addWidget(self.rectRadioButton, 0, 1, 1, 1)
        self.previewButton = QtWidgets.QPushButton(self.weightFunctionWidget)
        self.previewButton.setObjectName("previewButton")
        self.functionGridLayout.addWidget(self.previewButton, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.weightFunctionWidget)
        self.gridLayout.addWidget(self.functionGroupBox, 13, 0, 3, 4)
        self.filterAtomsResTabWidget = QtWidgets.QTabWidget(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterAtomsResTabWidget.sizePolicy().hasHeightForWidth())
        self.filterAtomsResTabWidget.setSizePolicy(sizePolicy)
        self.filterAtomsResTabWidget.setObjectName("filterAtomsResTabWidget")
        self.atomFilterPage = QtWidgets.QWidget()
        self.atomFilterPage.setObjectName("atomFilterPage")
        self.widget = QtWidgets.QWidget(self.atomFilterPage)
        self.widget.setGeometry(QtCore.QRect(0, -10, 561, 131))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.atomATypeField = QtWidgets.QLineEdit(self.widget)
        self.atomATypeField.setObjectName("atomATypeField")
        self.gridLayout_4.addWidget(self.atomATypeField, 3, 1, 1, 1)
        self.atomAIndexLabel = QtWidgets.QLabel(self.widget)
        self.atomAIndexLabel.setObjectName("atomAIndexLabel")
        self.gridLayout_4.addWidget(self.atomAIndexLabel, 0, 0, 1, 1)
        self.atomAIndexField = QtWidgets.QLineEdit(self.widget)
        self.atomAIndexField.setObjectName("atomAIndexField")
        self.gridLayout_4.addWidget(self.atomAIndexField, 0, 1, 1, 1)
        self.atomBIndexLabel = QtWidgets.QLabel(self.widget)
        self.atomBIndexLabel.setObjectName("atomBIndexLabel")
        self.gridLayout_4.addWidget(self.atomBIndexLabel, 0, 2, 1, 1)
        self.atomBIndexField = QtWidgets.QLineEdit(self.widget)
        self.atomBIndexField.setObjectName("atomBIndexField")
        self.gridLayout_4.addWidget(self.atomBIndexField, 0, 3, 1, 1)
        self.atomANameLabel = QtWidgets.QLabel(self.widget)
        self.atomANameLabel.setObjectName("atomANameLabel")
        self.gridLayout_4.addWidget(self.atomANameLabel, 1, 0, 1, 1)
        self.atomANameField = QtWidgets.QLineEdit(self.widget)
        self.atomANameField.setObjectName("atomANameField")
        self.gridLayout_4.addWidget(self.atomANameField, 1, 1, 1, 1)
        self.atomBNameLabel = QtWidgets.QLabel(self.widget)
        self.atomBNameLabel.setObjectName("atomBNameLabel")
        self.gridLayout_4.addWidget(self.atomBNameLabel, 1, 2, 1, 1)
        self.atomBNameField = QtWidgets.QLineEdit(self.widget)
        self.atomBNameField.setObjectName("atomBNameField")
        self.gridLayout_4.addWidget(self.atomBNameField, 1, 3, 1, 1)
        self.atomATypeLabel = QtWidgets.QLabel(self.widget)
        self.atomATypeLabel.setObjectName("atomATypeLabel")
        self.gridLayout_4.addWidget(self.atomATypeLabel, 3, 0, 1, 1)
        self.atomBTypeField = QtWidgets.QLineEdit(self.widget)
        self.atomBTypeField.setObjectName("atomBTypeField")
        self.gridLayout_4.addWidget(self.atomBTypeField, 3, 3, 1, 1)
        self.atomBTypeLabel = QtWidgets.QLabel(self.widget)
        self.atomBTypeLabel.setObjectName("atomBTypeLabel")
        self.gridLayout_4.addWidget(self.atomBTypeLabel, 3, 2, 1, 1)
        self.filterAtomsResTabWidget.addTab(self.atomFilterPage, "")
        self.residueFilterPage = QtWidgets.QWidget()
        self.residueFilterPage.setObjectName("residueFilterPage")
        self.residueFilterContainer = QtWidgets.QWidget(self.residueFilterPage)
        self.residueFilterContainer.setGeometry(QtCore.QRect(0, -10, 561, 91))
        self.residueFilterContainer.setObjectName("residueFilterContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.residueFilterContainer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.residARangeLabel = QtWidgets.QLabel(self.residueFilterContainer)
        self.residARangeLabel.setObjectName("residARangeLabel")
        self.gridLayout_3.addWidget(self.residARangeLabel, 0, 0, 1, 1)
        self.residARangeField = QtWidgets.QLineEdit(self.residueFilterContainer)
        self.residARangeField.setObjectName("residARangeField")
        self.gridLayout_3.addWidget(self.residARangeField, 0, 1, 1, 1)
        self.residBRangeLabel = QtWidgets.QLabel(self.residueFilterContainer)
        self.residBRangeLabel.setObjectName("residBRangeLabel")
        self.gridLayout_3.addWidget(self.residBRangeLabel, 0, 2, 1, 1)
        self.residBRangeField = QtWidgets.QLineEdit(self.residueFilterContainer)
        self.residBRangeField.setObjectName("residBRangeField")
        self.gridLayout_3.addWidget(self.residBRangeField, 0, 3, 1, 1)
        self.residANameLabel = QtWidgets.QLabel(self.residueFilterContainer)
        self.residANameLabel.setObjectName("residANameLabel")
        self.gridLayout_3.addWidget(self.residANameLabel, 1, 0, 1, 1)
        self.residANameField = QtWidgets.QLineEdit(self.residueFilterContainer)
        self.residANameField.setObjectName("residANameField")
        self.gridLayout_3.addWidget(self.residANameField, 1, 1, 1, 1)
        self.residBNameLabel = QtWidgets.QLabel(self.residueFilterContainer)
        self.residBNameLabel.setObjectName("residBNameLabel")
        self.gridLayout_3.addWidget(self.residBNameLabel, 1, 2, 1, 1)
        self.residBNameField = QtWidgets.QLineEdit(self.residueFilterContainer)
        self.residBNameField.setObjectName("residBNameField")
        self.gridLayout_3.addWidget(self.residBNameField, 1, 3, 1, 1)
        self.filterAtomsResTabWidget.addTab(self.residueFilterPage, "")
        self.gridLayout.addWidget(self.filterAtomsResTabWidget, 11, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.filterWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 5)
        self.scoreField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreField.sizePolicy().hasHeightForWidth())
        self.scoreField.setSizePolicy(sizePolicy)
        self.scoreField.setObjectName("scoreField")
        self.gridLayout.addWidget(self.scoreField, 5, 2, 1, 1)
        self.sortingOrderDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.sortingOrderDropdown.setObjectName("sortingOrderDropdown")
        self.sortingOrderDropdown.addItem("")
        self.sortingOrderDropdown.addItem("")
        self.gridLayout.addWidget(self.sortingOrderDropdown, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 4, 1, 1)
        self.activeSortingBox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeSortingBox.setObjectName("activeSortingBox")
        self.gridLayout.addWidget(self.activeSortingBox, 6, 3, 1, 1)
        self.sortingKeyDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.sortingKeyDropdown.setObjectName("sortingKeyDropdown")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.sortingKeyDropdown.addItem("")
        self.gridLayout.addWidget(self.sortingKeyDropdown, 6, 1, 1, 1)
        self.upperRangeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperRangeField.sizePolicy().hasHeightForWidth())
        self.upperRangeField.setSizePolicy(sizePolicy)
        self.upperRangeField.setObjectName("upperRangeField")
        self.gridLayout.addWidget(self.upperRangeField, 1, 2, 1, 1)
        self.filterRangeCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.filterRangeCheckbox.setObjectName("filterRangeCheckbox")
        self.gridLayout.addWidget(self.filterRangeCheckbox, 0, 3, 1, 1)
        self.sortingLabel = QtWidgets.QLabel(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortingLabel.sizePolicy().hasHeightForWidth())
        self.sortingLabel.setSizePolicy(sizePolicy)
        self.sortingLabel.setObjectName("sortingLabel")
        self.gridLayout.addWidget(self.sortingLabel, 6, 0, 1, 1)
        self.activeScoreCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeScoreCheckbox.setObjectName("activeScoreCheckbox")
        self.gridLayout.addWidget(self.activeScoreCheckbox, 5, 3, 1, 1)
        self.applyFilterButton = QtWidgets.QPushButton(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyFilterButton.sizePolicy().hasHeightForWidth())
        self.applyFilterButton.setSizePolicy(sizePolicy)
        self.applyFilterButton.setObjectName("applyFilterButton")
        self.gridLayout.addWidget(self.applyFilterButton, 15, 4, 1, 1)
        self.totalTimeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeField.sizePolicy().hasHeightForWidth())
        self.totalTimeField.setSizePolicy(sizePolicy)
        self.totalTimeField.setObjectName("totalTimeField")
        self.gridLayout.addWidget(self.totalTimeField, 4, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.filterWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.filterWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 5)
        self.toRangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.toRangeLabel.setObjectName("toRangeLabel")
        self.gridLayout.addWidget(self.toRangeLabel, 1, 1, 1, 1)
        self.rangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout.addWidget(self.rangeLabel, 0, 0, 1, 1)
        self.fromRangeLabel = QtWidgets.QLabel(self.filterWidget)
        self.fromRangeLabel.setObjectName("fromRangeLabel")
        self.gridLayout.addWidget(self.fromRangeLabel, 0, 1, 1, 1)
        self.lowerRangeField = QtWidgets.QLineEdit(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerRangeField.sizePolicy().hasHeightForWidth())
        self.lowerRangeField.setSizePolicy(sizePolicy)
        self.lowerRangeField.setObjectName("lowerRangeField")
        self.gridLayout.addWidget(self.lowerRangeField, 0, 2, 1, 1)
        self.activeTotalTimeCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.activeTotalTimeCheckbox.setObjectName("activeTotalTimeCheckbox")
        self.gridLayout.addWidget(self.activeTotalTimeCheckbox, 4, 3, 1, 1)
        self.compareScoreDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.compareScoreDropdown.setObjectName("compareScoreDropdown")
        self.compareScoreDropdown.addItem("")
        self.compareScoreDropdown.addItem("")
        self.gridLayout.addWidget(self.compareScoreDropdown, 5, 1, 1, 1)
        self.totalTimeLabel = QtWidgets.QLabel(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeLabel.sizePolicy().hasHeightForWidth())
        self.totalTimeLabel.setSizePolicy(sizePolicy)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.gridLayout.addWidget(self.totalTimeLabel, 4, 0, 1, 1)
        self.compareTotalTimeDropdown = QtWidgets.QComboBox(self.filterWidget)
        self.compareTotalTimeDropdown.setObjectName("compareTotalTimeDropdown")
        self.compareTotalTimeDropdown.addItem("")
        self.compareTotalTimeDropdown.addItem("")
        self.gridLayout.addWidget(self.compareTotalTimeDropdown, 4, 1, 1, 1)
        self.meanDropdown = QtWidgets.QComboBox(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanDropdown.sizePolicy().hasHeightForWidth())
        self.meanDropdown.setSizePolicy(sizePolicy)
        self.meanDropdown.setObjectName("meanDropdown")
        self.meanDropdown.addItem("")
        self.meanDropdown.addItem("")
        self.meanDropdown.addItem("")
        self.gridLayout.addWidget(self.meanDropdown, 5, 0, 1, 1)
        self.selectOnlyToolbox = QtWidgets.QComboBox(self.filterWidget)
        self.selectOnlyToolbox.setObjectName("selectOnlyToolbox")
        self.selectOnlyToolbox.addItem("")
        self.selectOnlyToolbox.addItem("")
        self.selectOnlyToolbox.addItem("")
        self.selectOnlyToolbox.addItem("")
        self.gridLayout.addWidget(self.selectOnlyToolbox, 7, 1, 1, 1)
        self.sortingLabel_2 = QtWidgets.QLabel(self.filterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortingLabel_2.sizePolicy().hasHeightForWidth())
        self.sortingLabel_2.setSizePolicy(sizePolicy)
        self.sortingLabel_2.setObjectName("sortingLabel_2")
        self.gridLayout.addWidget(self.sortingLabel_2, 7, 0, 1, 1)
        self.onlyBoxActiveCheckbox = QtWidgets.QCheckBox(self.filterWidget)
        self.onlyBoxActiveCheckbox.setObjectName("onlyBoxActiveCheckbox")
        self.gridLayout.addWidget(self.onlyBoxActiveCheckbox, 7, 3, 1, 1)
        self.functionGroupBox.raise_()
        self.functionActiveCheckbox.raise_()
        self.applyFilterButton.raise_()
        self.activeSortingBox.raise_()
        self.filterRangeCheckbox.raise_()
        self.upperRangeField.raise_()
        self.sortingLabel.raise_()
        self.activeScoreCheckbox.raise_()
        self.totalTimeField.raise_()
        self.line_3.raise_()
        self.line.raise_()
        self.toRangeLabel.raise_()
        self.rangeLabel.raise_()
        self.fromRangeLabel.raise_()
        self.line_2.raise_()
        self.activeTotalTimeCheckbox.raise_()
        self.compareScoreDropdown.raise_()
        self.totalTimeLabel.raise_()
        self.compareTotalTimeDropdown.raise_()
        self.meanDropdown.raise_()
        self.sortingKeyDropdown.raise_()
        self.scoreField.raise_()
        self.sortingOrderDropdown.raise_()
        self.filterAtomsResTabWidget.raise_()
        self.lowerRangeField.raise_()
        self.selectOnlyToolbox.raise_()
        self.sortingLabel_2.raise_()
        self.onlyBoxActiveCheckbox.raise_()
        settingsWindowWidget.addTab(self.filterTab, "")
        self.colorsTab = QtWidgets.QWidget()
        self.colorsTab.setObjectName("colorsTab")
        self.colorWidget = QtWidgets.QWidget(self.colorsTab)
        self.colorWidget.setGeometry(QtCore.QRect(0, 0, 591, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorWidget.sizePolicy().hasHeightForWidth())
        self.colorWidget.setSizePolicy(sizePolicy)
        self.colorWidget.setObjectName("colorWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.colorWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.framesLabel = QtWidgets.QLabel(self.colorWidget)
        self.framesLabel.setObjectName("framesLabel")
        self.gridLayout_5.addWidget(self.framesLabel, 0, 0, 1, 1)
        self.pickColorButton = QtWidgets.QPushButton(self.colorWidget)
        self.pickColorButton.setObjectName("pickColorButton")
        self.gridLayout_5.addWidget(self.pickColorButton, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.bbscScoreRadioButton = QtWidgets.QRadioButton(self.colorWidget)
        self.bbscScoreRadioButton.setChecked(True)
        self.bbscScoreRadioButton.setObjectName("bbscScoreRadioButton")
        self.gridLayout_5.addWidget(self.bbscScoreRadioButton, 0, 1, 1, 1)
        self.customColorRadioButton = QtWidgets.QRadioButton(self.colorWidget)
        self.customColorRadioButton.setObjectName("customColorRadioButton")
        self.gridLayout_5.addWidget(self.customColorRadioButton, 0, 2, 1, 1)
        self.applyColorButton = QtWidgets.QPushButton(self.colorWidget)
        self.applyColorButton.setObjectName("applyColorButton")
        self.gridLayout_5.addWidget(self.applyColorButton, 2, 3, 1, 1)
        settingsWindowWidget.addTab(self.colorsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsWidget = QtWidgets.QWidget(self.settingsTab)
        self.settingsWidget.setGeometry(QtCore.QRect(-1, -1, 581, 431))
        self.settingsWidget.setObjectName("settingsWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingsWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.thresholdLabel = QtWidgets.QLabel(self.settingsWidget)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.gridLayout_2.addWidget(self.thresholdLabel, 1, 0, 1, 1)
        self.thresholdField = QtWidgets.QLineEdit(self.settingsWidget)
        self.thresholdField.setClearButtonEnabled(True)
        self.thresholdField.setObjectName("thresholdField")
        self.gridLayout_2.addWidget(self.thresholdField, 1, 1, 1, 1)
        self.applySettingsButton = QtWidgets.QPushButton(self.settingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applySettingsButton.sizePolicy().hasHeightForWidth())
        self.applySettingsButton.setSizePolicy(sizePolicy)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.gridLayout_2.addWidget(self.applySettingsButton, 4, 2, 1, 1)
        self.nsPerFrameField = QtWidgets.QLineEdit(self.settingsWidget)
        self.nsPerFrameField.setClearButtonEnabled(True)
        self.nsPerFrameField.setObjectName("nsPerFrameField")
        self.gridLayout_2.addWidget(self.nsPerFrameField, 0, 1, 1, 1)
        self.nsPerFrameLabel = QtWidgets.QLabel(self.settingsWidget)
        self.nsPerFrameLabel.setObjectName("nsPerFrameLabel")
        self.gridLayout_2.addWidget(self.nsPerFrameLabel, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 2)
        settingsWindowWidget.addTab(self.settingsTab, "")

        self.retranslateUi(settingsWindowWidget)
        settingsWindowWidget.setCurrentIndex(0)
        self.filterAtomsResTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settingsWindowWidget)

    def retranslateUi(self, settingsWindowWidget):
        _translate = QtCore.QCoreApplication.translate
        settingsWindowWidget.setWindowTitle(_translate("settingsWindowWidget", "Preferences"))
        self.functionActiveCheckbox.setText(_translate("settingsWindowWidget", "weight active"))
        self.functionGroupBox.setTitle(_translate("settingsWindowWidget", "Frame weight functions"))
        self.sigmoidRadioButton.setText(_translate("settingsWindowWidget", "sigmoid"))
        self.linRadioButton.setText(_translate("settingsWindowWidget", "linear"))
        self.rectRadioButton.setText(_translate("settingsWindowWidget", "rectangle"))
        self.previewButton.setText(_translate("settingsWindowWidget", "Preview"))
        self.atomATypeField.setText(_translate("settingsWindowWidget", "all"))
        self.atomAIndexLabel.setText(_translate("settingsWindowWidget", "range A:"))
        self.atomAIndexField.setText(_translate("settingsWindowWidget", "all"))
        self.atomBIndexLabel.setText(_translate("settingsWindowWidget", "range B:"))
        self.atomBIndexField.setText(_translate("settingsWindowWidget", "all"))
        self.atomANameLabel.setText(_translate("settingsWindowWidget", "names A:"))
        self.atomANameField.setText(_translate("settingsWindowWidget", "all"))
        self.atomBNameLabel.setText(_translate("settingsWindowWidget", "names B:"))
        self.atomBNameField.setText(_translate("settingsWindowWidget", "all"))
        self.atomATypeLabel.setText(_translate("settingsWindowWidget", "types A:"))
        self.atomBTypeField.setText(_translate("settingsWindowWidget", "all"))
        self.atomBTypeLabel.setText(_translate("settingsWindowWidget", "types B:"))
        self.filterAtomsResTabWidget.setTabText(self.filterAtomsResTabWidget.indexOf(self.atomFilterPage), _translate("settingsWindowWidget", "Atoms"))
        self.residARangeLabel.setText(_translate("settingsWindowWidget", "range A:"))
        self.residARangeField.setText(_translate("settingsWindowWidget", "all"))
        self.residBRangeLabel.setText(_translate("settingsWindowWidget", "range B:"))
        self.residBRangeField.setText(_translate("settingsWindowWidget", "all"))
        self.residANameLabel.setText(_translate("settingsWindowWidget", "names A:"))
        self.residANameField.setText(_translate("settingsWindowWidget", "all"))
        self.residBNameLabel.setText(_translate("settingsWindowWidget", "names B:"))
        self.residBNameField.setText(_translate("settingsWindowWidget", "all"))
        self.filterAtomsResTabWidget.setTabText(self.filterAtomsResTabWidget.indexOf(self.residueFilterPage), _translate("settingsWindowWidget", "Residues"))
        self.scoreField.setText(_translate("settingsWindowWidget", "0"))
        self.sortingOrderDropdown.setItemText(0, _translate("settingsWindowWidget", "asc"))
        self.sortingOrderDropdown.setItemText(1, _translate("settingsWindowWidget", "desc"))
        self.activeSortingBox.setText(_translate("settingsWindowWidget", "active"))
        self.sortingKeyDropdown.setItemText(0, _translate("settingsWindowWidget", "mean"))
        self.sortingKeyDropdown.setItemText(1, _translate("settingsWindowWidget", "median"))
        self.sortingKeyDropdown.setItemText(2, _translate("settingsWindowWidget", "bb/sc type"))
        self.sortingKeyDropdown.setItemText(3, _translate("settingsWindowWidget", "contact type"))
        self.sortingKeyDropdown.setItemText(4, _translate("settingsWindowWidget", "total time"))
        self.sortingKeyDropdown.setItemText(5, _translate("settingsWindowWidget", "mean lifetime"))
        self.sortingKeyDropdown.setItemText(6, _translate("settingsWindowWidget", "median lifetime"))
        self.sortingKeyDropdown.setItemText(7, _translate("settingsWindowWidget", "resid A"))
        self.sortingKeyDropdown.setItemText(8, _translate("settingsWindowWidget", "resid B"))
        self.upperRangeField.setText(_translate("settingsWindowWidget", "end"))
        self.filterRangeCheckbox.setText(_translate("settingsWindowWidget", "filter range"))
        self.sortingLabel.setText(_translate("settingsWindowWidget", "sorting:"))
        self.activeScoreCheckbox.setText(_translate("settingsWindowWidget", "active"))
        self.applyFilterButton.setText(_translate("settingsWindowWidget", "Apply"))
        self.totalTimeField.setText(_translate("settingsWindowWidget", "0"))
        self.toRangeLabel.setText(_translate("settingsWindowWidget", "to:"))
        self.rangeLabel.setText(_translate("settingsWindowWidget", "Display range:"))
        self.fromRangeLabel.setText(_translate("settingsWindowWidget", "from:"))
        self.lowerRangeField.setText(_translate("settingsWindowWidget", "1"))
        self.activeTotalTimeCheckbox.setText(_translate("settingsWindowWidget", "active"))
        self.compareScoreDropdown.setCurrentText(_translate("settingsWindowWidget", "greater"))
        self.compareScoreDropdown.setItemText(0, _translate("settingsWindowWidget", "greater"))
        self.compareScoreDropdown.setItemText(1, _translate("settingsWindowWidget", "smaller"))
        self.totalTimeLabel.setText(_translate("settingsWindowWidget", "total time:"))
        self.compareTotalTimeDropdown.setCurrentText(_translate("settingsWindowWidget", "greater"))
        self.compareTotalTimeDropdown.setItemText(0, _translate("settingsWindowWidget", "greater"))
        self.compareTotalTimeDropdown.setItemText(1, _translate("settingsWindowWidget", "smaller"))
        self.meanDropdown.setItemText(0, _translate("settingsWindowWidget", "mean"))
        self.meanDropdown.setItemText(1, _translate("settingsWindowWidget", "median"))
        self.meanDropdown.setItemText(2, _translate("settingsWindowWidget", "hbond perc."))
        self.selectOnlyToolbox.setItemText(0, _translate("settingsWindowWidget", "hbonds"))
        self.selectOnlyToolbox.setItemText(1, _translate("settingsWindowWidget", "hydrophobic"))
        self.selectOnlyToolbox.setItemText(2, _translate("settingsWindowWidget", "saltbridges"))
        self.selectOnlyToolbox.setItemText(3, _translate("settingsWindowWidget", "unknown"))
        self.sortingLabel_2.setText(_translate("settingsWindowWidget", "only:"))
        self.onlyBoxActiveCheckbox.setText(_translate("settingsWindowWidget", "active"))
        settingsWindowWidget.setTabText(settingsWindowWidget.indexOf(self.filterTab), _translate("settingsWindowWidget", "Filters"))
        self.framesLabel.setText(_translate("settingsWindowWidget", "Frames:"))
        self.pickColorButton.setText(_translate("settingsWindowWidget", "Pick"))
        self.bbscScoreRadioButton.setText(_translate("settingsWindowWidget", "backbone/sidechain score"))
        self.customColorRadioButton.setText(_translate("settingsWindowWidget", "custom"))
        self.applyColorButton.setText(_translate("settingsWindowWidget", "Apply"))
        settingsWindowWidget.setTabText(settingsWindowWidget.indexOf(self.colorsTab), _translate("settingsWindowWidget", "Colors"))
        self.thresholdLabel.setText(_translate("settingsWindowWidget", "Threshold:"))
        self.thresholdField.setText(_translate("settingsWindowWidget", "0.0"))
        self.applySettingsButton.setText(_translate("settingsWindowWidget", "Apply"))
        self.nsPerFrameField.setText(_translate("settingsWindowWidget", "1.0"))
        self.nsPerFrameLabel.setText(_translate("settingsWindowWidget", "Nanoseconds per frame:"))
        settingsWindowWidget.setTabText(settingsWindowWidget.indexOf(self.settingsTab), _translate("settingsWindowWidget", "Settings"))

