# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Detail(object):
    def setupUi(self, Detail):
        Detail.setObjectName("Detail")
        Detail.setWindowModality(QtCore.Qt.WindowModal)
        Detail.resize(788, 672)
        self.gridLayout = QtWidgets.QGridLayout(Detail)
        self.gridLayout.setObjectName("gridLayout")
        self.labelBackboneSidechainA = QtWidgets.QLabel(Detail)
        self.labelBackboneSidechainA.setText("")
        self.labelBackboneSidechainA.setObjectName("labelBackboneSidechainA")
        self.gridLayout.addWidget(self.labelBackboneSidechainA, 3, 1, 1, 1)
        self.labelMedianLifetime = QtWidgets.QLabel(Detail)
        self.labelMedianLifetime.setText("")
        self.labelMedianLifetime.setObjectName("labelMedianLifetime")
        self.gridLayout.addWidget(self.labelMedianLifetime, 3, 3, 1, 1)
        self.plotWidget = QtWidgets.QWidget(Detail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(370, 128))
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.plotWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plotGridLayout = QtWidgets.QGridLayout()
        self.plotGridLayout.setObjectName("plotGridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.plotGridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.plotGridLayout, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.plotWidget, 6, 0, 1, 4)
        self.line = QtWidgets.QFrame(Detail)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 4)
        self.labelMeanScore = QtWidgets.QLabel(Detail)
        self.labelMeanScore.setText("")
        self.labelMeanScore.setObjectName("labelMeanScore")
        self.gridLayout.addWidget(self.labelMeanScore, 2, 3, 1, 1)
        self.labelThreshold = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelThreshold.setFont(font)
        self.labelThreshold.setText("")
        self.labelThreshold.setObjectName("labelThreshold")
        self.gridLayout.addWidget(self.labelThreshold, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.labelMedianScore = QtWidgets.QLabel(Detail)
        self.labelMedianScore.setText("")
        self.labelMedianScore.setObjectName("labelMedianScore")
        self.gridLayout.addWidget(self.labelMedianScore, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.labelTotalTime = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelTotalTime.setFont(font)
        self.labelTotalTime.setText("")
        self.labelTotalTime.setObjectName("labelTotalTime")
        self.gridLayout.addWidget(self.labelTotalTime, 0, 1, 1, 1)
        self.savePlotButton = QtWidgets.QPushButton(Detail)
        self.savePlotButton.setObjectName("savePlotButton")
        self.gridLayout.addWidget(self.savePlotButton, 7, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.attributeBox = QtWidgets.QComboBox(Detail)
        self.attributeBox.setObjectName("attributeBox")
        self.attributeBox.addItem("")
        self.gridLayout.addWidget(self.attributeBox, 7, 0, 1, 1)
        self.plotButton = QtWidgets.QPushButton(Detail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotButton.sizePolicy().hasHeightForWidth())
        self.plotButton.setSizePolicy(sizePolicy)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout.addWidget(self.plotButton, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.labelBackboneSidechainB = QtWidgets.QLabel(Detail)
        self.labelBackboneSidechainB.setText("")
        self.labelBackboneSidechainB.setObjectName("labelBackboneSidechainB")
        self.gridLayout.addWidget(self.labelBackboneSidechainB, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Detail)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.labelMeanLifetime = QtWidgets.QLabel(Detail)
        self.labelMeanLifetime.setText("")
        self.labelMeanLifetime.setObjectName("labelMeanLifetime")
        self.gridLayout.addWidget(self.labelMeanLifetime, 4, 3, 1, 1)

        self.retranslateUi(Detail)
        QtCore.QMetaObject.connectSlotsByName(Detail)

    def retranslateUi(self, Detail):
        _translate = QtCore.QCoreApplication.translate
        Detail.setWindowTitle(_translate("Detail", "Statistics"))
        self.label_5.setText(_translate("Detail", "Median Contact Score: "))
        self.label.setText(_translate("Detail", "Current Threshold:"))
        self.savePlotButton.setText(_translate("Detail", "Save"))
        self.label_6.setText(_translate("Detail", "Mean Contact Score:"))
        self.attributeBox.setItemText(0, _translate("Detail", "Score"))
        self.plotButton.setText(_translate("Detail", "Plot"))
        self.label_2.setText(_translate("Detail", "Total Time [ns]:"))
        self.label_4.setText(_translate("Detail", "bb/sc score (A):"))
        self.label_3.setText(_translate("Detail", "Median Lifetime:"))
        self.label_9.setText(_translate("Detail", "bb/sc score (B):"))
        self.label_11.setText(_translate("Detail", "Mean Lifetime:"))

