# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mergeSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeSlider.sizePolicy().hasHeightForWidth())
        self.mergeSlider.setSizePolicy(sizePolicy)
        self.mergeSlider.setMinimum(1)
        self.mergeSlider.setMaximum(10)
        self.mergeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mergeSlider.setInvertedAppearance(False)
        self.mergeSlider.setInvertedControls(False)
        self.mergeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mergeSlider.setTickInterval(1)
        self.mergeSlider.setObjectName("mergeSlider")
        self.gridLayout.addWidget(self.mergeSlider, 0, 1, 1, 1)
        self.openPreferencesButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPreferencesButton.sizePolicy().hasHeightForWidth())
        self.openPreferencesButton.setSizePolicy(sizePolicy)
        self.openPreferencesButton.setObjectName("openPreferencesButton")
        self.gridLayout.addWidget(self.openPreferencesButton, 0, 6, 1, 1)
        self.analysisButton = QtWidgets.QPushButton(self.centralwidget)
        self.analysisButton.setObjectName("analysisButton")
        self.gridLayout.addWidget(self.analysisButton, 0, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1014, 539))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 8)
        self.contactAreaButton = QtWidgets.QPushButton(self.centralwidget)
        self.contactAreaButton.setObjectName("contactAreaButton")
        self.gridLayout.addWidget(self.contactAreaButton, 0, 7, 1, 1)
        self.statisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.statisticsButton.setObjectName("statisticsButton")
        self.gridLayout.addWidget(self.statisticsButton, 0, 4, 1, 1)
        self.zoomSliderLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSliderLabel.sizePolicy().hasHeightForWidth())
        self.zoomSliderLabel.setSizePolicy(sizePolicy)
        self.zoomSliderLabel.setObjectName("zoomSliderLabel")
        self.gridLayout.addWidget(self.zoomSliderLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRun_VMD_contact_search = QtWidgets.QAction(MainWindow)
        self.actionRun_VMD_contact_search.setObjectName("actionRun_VMD_contact_search")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionImport_Session = QtWidgets.QAction(MainWindow)
        self.actionImport_Session.setObjectName("actionImport_Session")
        self.actionExport_Session = QtWidgets.QAction(MainWindow)
        self.actionExport_Session.setObjectName("actionExport_Session")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionShow_Info = QtWidgets.QAction(MainWindow)
        self.actionShow_Info.setObjectName("actionShow_Info")
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport_Session)
        self.menuFile.addAction(self.actionExport_Session)
        self.menuFile.addAction(self.actionDefault)
        self.menuAbout.addAction(self.actionShow_Info)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openPreferencesButton.setText(_translate("MainWindow", "Preferences"))
        self.analysisButton.setText(_translate("MainWindow", "Analyze"))
        self.contactAreaButton.setText(_translate("MainWindow", "Contact areas"))
        self.statisticsButton.setText(_translate("MainWindow", "Statistics"))
        self.zoomSliderLabel.setText(_translate("MainWindow", "Zoom:"))
        self.label.setText(_translate("MainWindow", "Current selections:"))
        self.label_2.setText(_translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "None"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionRun_VMD_contact_search.setText(_translate("MainWindow", "Run VMD contact search"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionLoad_Data.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionImport_Session.setText(_translate("MainWindow", "Import Session"))
        self.actionImport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionExport_Session.setText(_translate("MainWindow", "Export Session"))
        self.actionExport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionDefault.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShow_Info.setText(_translate("MainWindow", "Show Info"))

