# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 415)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trajectoryTableView = QtWidgets.QTableView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trajectoryTableView.sizePolicy().hasHeightForWidth())
        self.trajectoryTableView.setSizePolicy(sizePolicy)
        self.trajectoryTableView.setObjectName("trajectoryTableView")
        self.trajectoryTableView.horizontalHeader().setVisible(False)
        self.trajectoryTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.trajectoryTableView, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonTopology = QtWidgets.QPushButton(Dialog)
        self.buttonTopology.setObjectName("buttonTopology")
        self.horizontalLayout_3.addWidget(self.buttonTopology)
        self.buttonTrajectory = QtWidgets.QPushButton(Dialog)
        self.buttonTrajectory.setObjectName("buttonTrajectory")
        self.horizontalLayout_3.addWidget(self.buttonTrajectory)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cutoffField = QtWidgets.QLineEdit(Dialog)
        self.cutoffField.setObjectName("cutoffField")
        self.gridLayout_3.addWidget(self.cutoffField, 0, 1, 1, 1)
        self.cutoffAngleField = QtWidgets.QLineEdit(Dialog)
        self.cutoffAngleField.setObjectName("cutoffAngleField")
        self.gridLayout_3.addWidget(self.cutoffAngleField, 1, 1, 1, 1)
        self.selection1Field = QtWidgets.QLineEdit(Dialog)
        self.selection1Field.setObjectName("selection1Field")
        self.gridLayout_3.addWidget(self.selection1Field, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.cutoffHbondField = QtWidgets.QLineEdit(Dialog)
        self.cutoffHbondField.setObjectName("cutoffHbondField")
        self.gridLayout_3.addWidget(self.cutoffHbondField, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.selection2Field = QtWidgets.QLineEdit(Dialog)
        self.selection2Field.setObjectName("selection2Field")
        self.gridLayout_3.addWidget(self.selection2Field, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.topFileDisplay = QtWidgets.QLabel(Dialog)
        self.topFileDisplay.setObjectName("topFileDisplay")
        self.gridLayout_4.addWidget(self.topFileDisplay, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.cutoffField, self.cutoffAngleField)
        Dialog.setTabOrder(self.cutoffAngleField, self.cutoffHbondField)
        Dialog.setTabOrder(self.cutoffHbondField, self.selection1Field)
        Dialog.setTabOrder(self.selection1Field, self.selection2Field)
        Dialog.setTabOrder(self.selection2Field, self.buttonTopology)
        Dialog.setTabOrder(self.buttonTopology, self.buttonTrajectory)
        Dialog.setTabOrder(self.buttonTrajectory, self.trajectoryTableView)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Load Data"))
        self.buttonTopology.setText(_translate("Dialog", "Topology"))
        self.buttonTrajectory.setText(_translate("Dialog", "Add Trajectory"))
        self.cutoffField.setText(_translate("Dialog", "5.0"))
        self.cutoffAngleField.setText(_translate("Dialog", "120"))
        self.label.setText(_translate("Dialog", "distance cutoff:"))
        self.label_2.setText(_translate("Dialog", "angle cutoff:"))
        self.cutoffHbondField.setText(_translate("Dialog", "2.5"))
        self.label_4.setText(_translate("Dialog", "selection 1:"))
        self.label_3.setText(_translate("Dialog", "acc-h cutoff:"))
        self.label_5.setText(_translate("Dialog", "selection 2:"))
        self.label_6.setText(_translate("Dialog", "Topology:"))
        self.topFileDisplay.setText(_translate("Dialog", "-"))

