# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainQtGui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.contactAreaButton = QtWidgets.QPushButton(self.centralwidget)
        self.contactAreaButton.setObjectName("contactAreaButton")
        self.gridLayout.addWidget(self.contactAreaButton, 0, 8, 1, 1)
        self.statisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.statisticsButton.setObjectName("statisticsButton")
        self.gridLayout.addWidget(self.statisticsButton, 0, 6, 1, 1)
        self.mergeSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeSlider.sizePolicy().hasHeightForWidth())
        self.mergeSlider.setSizePolicy(sizePolicy)
        self.mergeSlider.setMinimum(1)
        self.mergeSlider.setMaximum(10)
        self.mergeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mergeSlider.setInvertedAppearance(False)
        self.mergeSlider.setInvertedControls(False)
        self.mergeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mergeSlider.setTickInterval(1)
        self.mergeSlider.setObjectName("mergeSlider")
        self.gridLayout.addWidget(self.mergeSlider, 0, 1, 1, 1)
        self.zoomSliderLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSliderLabel.sizePolicy().hasHeightForWidth())
        self.zoomSliderLabel.setSizePolicy(sizePolicy)
        self.zoomSliderLabel.setObjectName("zoomSliderLabel")
        self.gridLayout.addWidget(self.zoomSliderLabel, 0, 0, 1, 1)
        self.openPreferencesButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPreferencesButton.sizePolicy().hasHeightForWidth())
        self.openPreferencesButton.setSizePolicy(sizePolicy)
        self.openPreferencesButton.setObjectName("openPreferencesButton")
        self.gridLayout.addWidget(self.openPreferencesButton, 0, 7, 1, 1)
        self.analysisButton = QtWidgets.QPushButton(self.centralwidget)
        self.analysisButton.setObjectName("analysisButton")
        self.gridLayout.addWidget(self.analysisButton, 0, 5, 1, 1)
        self.infoWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoWidget.sizePolicy().hasHeightForWidth())
        self.infoWidget.setSizePolicy(sizePolicy)
        self.infoWidget.setObjectName("infoWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.infoWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selection1label = QtWidgets.QLabel(self.infoWidget)
        self.selection1label.setObjectName("selection1label")
        self.gridLayout_2.addWidget(self.selection1label, 0, 5, 1, 1)
        self.selection1 = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection1.sizePolicy().hasHeightForWidth())
        self.selection1.setSizePolicy(sizePolicy)
        self.selection1.setObjectName("selection1")
        self.gridLayout_2.addWidget(self.selection1, 0, 4, 1, 1)
        self.status = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 0, 0, 1, 1)
        self.selection2label = QtWidgets.QLabel(self.infoWidget)
        self.selection2label.setObjectName("selection2label")
        self.gridLayout_2.addWidget(self.selection2label, 0, 7, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.infoWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_2.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.selection2 = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection2.sizePolicy().hasHeightForWidth())
        self.selection2.setSizePolicy(sizePolicy)
        self.selection2.setObjectName("selection2")
        self.gridLayout_2.addWidget(self.selection2, 0, 6, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.infoWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.infoWidget, 3, 0, 1, 9)
        self.visModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.visModeButton.setObjectName("visModeButton")
        self.gridLayout.addWidget(self.visModeButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        self.rangeLabel = QtWidgets.QLabel(self.frame)
        self.rangeLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout_3.addWidget(self.rangeLabel, 0, 1, 1, 1)
        self.upperRangeField = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperRangeField.sizePolicy().hasHeightForWidth())
        self.upperRangeField.setSizePolicy(sizePolicy)
        self.upperRangeField.setMaximumSize(QtCore.QSize(50, 16777215))
        self.upperRangeField.setObjectName("upperRangeField")
        self.gridLayout_3.addWidget(self.upperRangeField, 0, 4, 1, 1)
        self.lowerRangeField = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerRangeField.sizePolicy().hasHeightForWidth())
        self.lowerRangeField.setSizePolicy(sizePolicy)
        self.lowerRangeField.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lowerRangeField.setObjectName("lowerRangeField")
        self.gridLayout_3.addWidget(self.lowerRangeField, 0, 2, 1, 1)
        self.filterRangeCheckbox = QtWidgets.QCheckBox(self.frame)
        self.filterRangeCheckbox.setObjectName("filterRangeCheckbox")
        self.gridLayout_3.addWidget(self.filterRangeCheckbox, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 1, 1, 4)
        self.gridLayout.addWidget(self.frame, 2, 6, 1, 3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1068, 708))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.upperRangeField.raise_()
        self.lowerRangeField.raise_()
        self.rangeLabel.raise_()
        self.filterRangeCheckbox.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRun_VMD_contact_search = QtWidgets.QAction(MainWindow)
        self.actionRun_VMD_contact_search.setObjectName("actionRun_VMD_contact_search")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionImport_Session = QtWidgets.QAction(MainWindow)
        self.actionImport_Session.setObjectName("actionImport_Session")
        self.actionExport_Session = QtWidgets.QAction(MainWindow)
        self.actionExport_Session.setObjectName("actionExport_Session")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionShow_Info = QtWidgets.QAction(MainWindow)
        self.actionShow_Info.setObjectName("actionShow_Info")
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport_Session)
        self.menuFile.addAction(self.actionExport_Session)
        self.menuFile.addAction(self.actionDefault)
        self.menuAbout.addAction(self.actionShow_Info)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.contactAreaButton.setText(_translate("MainWindow", "Contact areas"))
        self.statisticsButton.setText(_translate("MainWindow", "Statistics"))
        self.zoomSliderLabel.setText(_translate("MainWindow", "Zoom:"))
        self.openPreferencesButton.setText(_translate("MainWindow", "Preferences"))
        self.analysisButton.setText(_translate("MainWindow", "Analyze"))
        self.selection1label.setText(_translate("MainWindow", "-"))
        self.selection1.setText(_translate("MainWindow", "Selection 1:"))
        self.status.setText(_translate("MainWindow", "Status:"))
        self.selection2label.setText(_translate("MainWindow", "-"))
        self.statusLabel.setText(_translate("MainWindow", "-"))
        self.selection2.setText(_translate("MainWindow", "Selection 2:"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.visModeButton.setText(_translate("MainWindow", "Vismode"))
        self.label.setText(_translate("MainWindow", "to"))
        self.rangeLabel.setText(_translate("MainWindow", "Timeline range"))
        self.upperRangeField.setText(_translate("MainWindow", "end"))
        self.lowerRangeField.setText(_translate("MainWindow", "1"))
        self.filterRangeCheckbox.setText(_translate("MainWindow", "filter range"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionRun_VMD_contact_search.setText(_translate("MainWindow", "Run VMD contact search"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionLoad_Data.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionImport_Session.setText(_translate("MainWindow", "Import Session"))
        self.actionImport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionExport_Session.setText(_translate("MainWindow", "Export Session"))
        self.actionExport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionDefault.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShow_Info.setText(_translate("MainWindow", "Show Info"))

