# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainQtGui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.visModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.visModeButton.setObjectName("visModeButton")
        self.gridLayout.addWidget(self.visModeButton, 0, 3, 1, 2)
        self.infoWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoWidget.sizePolicy().hasHeightForWidth())
        self.infoWidget.setSizePolicy(sizePolicy)
        self.infoWidget.setObjectName("infoWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.infoWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selection1label = QtWidgets.QLabel(self.infoWidget)
        self.selection1label.setObjectName("selection1label")
        self.gridLayout_2.addWidget(self.selection1label, 0, 5, 1, 1)
        self.selection1 = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection1.sizePolicy().hasHeightForWidth())
        self.selection1.setSizePolicy(sizePolicy)
        self.selection1.setObjectName("selection1")
        self.gridLayout_2.addWidget(self.selection1, 0, 4, 1, 1)
        self.status = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 0, 0, 1, 1)
        self.selection2label = QtWidgets.QLabel(self.infoWidget)
        self.selection2label.setObjectName("selection2label")
        self.gridLayout_2.addWidget(self.selection2label, 0, 7, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.infoWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_2.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.selection2 = QtWidgets.QLabel(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection2.sizePolicy().hasHeightForWidth())
        self.selection2.setSizePolicy(sizePolicy)
        self.selection2.setObjectName("selection2")
        self.gridLayout_2.addWidget(self.selection2, 0, 6, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.infoWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.infoWidget, 3, 0, 1, 10)
        self.filterFrame = QtWidgets.QFrame(self.centralwidget)
        self.filterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filterFrame.setObjectName("filterFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.filterFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.zoomSliderLabel = QtWidgets.QLabel(self.filterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSliderLabel.sizePolicy().hasHeightForWidth())
        self.zoomSliderLabel.setSizePolicy(sizePolicy)
        self.zoomSliderLabel.setObjectName("zoomSliderLabel")
        self.gridLayout_3.addWidget(self.zoomSliderLabel, 0, 1, 1, 1)
        self.toLabel = QtWidgets.QLabel(self.filterFrame)
        self.toLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.toLabel.setObjectName("toLabel")
        self.gridLayout_3.addWidget(self.toLabel, 2, 3, 1, 1)
        self.rangeLabel = QtWidgets.QLabel(self.filterFrame)
        self.rangeLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout_3.addWidget(self.rangeLabel, 2, 1, 1, 1)
        self.sepLine2 = QtWidgets.QFrame(self.filterFrame)
        self.sepLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.sepLine2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sepLine2.setObjectName("sepLine2")
        self.gridLayout_3.addWidget(self.sepLine2, 4, 1, 1, 4)
        self.upperRangeField = QtWidgets.QLineEdit(self.filterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperRangeField.sizePolicy().hasHeightForWidth())
        self.upperRangeField.setSizePolicy(sizePolicy)
        self.upperRangeField.setMaximumSize(QtCore.QSize(50, 16777215))
        self.upperRangeField.setObjectName("upperRangeField")
        self.gridLayout_3.addWidget(self.upperRangeField, 2, 4, 1, 1)
        self.lowerRangeField = QtWidgets.QLineEdit(self.filterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerRangeField.sizePolicy().hasHeightForWidth())
        self.lowerRangeField.setSizePolicy(sizePolicy)
        self.lowerRangeField.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lowerRangeField.setObjectName("lowerRangeField")
        self.gridLayout_3.addWidget(self.lowerRangeField, 2, 2, 1, 1)
        self.filterRangeCheckbox = QtWidgets.QCheckBox(self.filterFrame)
        self.filterRangeCheckbox.setObjectName("filterRangeCheckbox")
        self.gridLayout_3.addWidget(self.filterRangeCheckbox, 3, 1, 1, 1)
        self.mergeSlider = QtWidgets.QSlider(self.filterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeSlider.sizePolicy().hasHeightForWidth())
        self.mergeSlider.setSizePolicy(sizePolicy)
        self.mergeSlider.setMinimum(1)
        self.mergeSlider.setMaximum(10)
        self.mergeSlider.setSingleStep(1)
        self.mergeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mergeSlider.setInvertedAppearance(False)
        self.mergeSlider.setInvertedControls(False)
        self.mergeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mergeSlider.setTickInterval(1)
        self.mergeSlider.setObjectName("mergeSlider")
        self.gridLayout_3.addWidget(self.mergeSlider, 0, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.filterFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 1, 1, 4)
        self.gridLayout.addWidget(self.filterFrame, 2, 8, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 990, 708))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 8)
        self.statisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.statisticsButton.setObjectName("statisticsButton")
        self.gridLayout.addWidget(self.statisticsButton, 0, 2, 1, 1)
        self.analysisButton = QtWidgets.QPushButton(self.centralwidget)
        self.analysisButton.setObjectName("analysisButton")
        self.gridLayout.addWidget(self.analysisButton, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRun_VMD_contact_search = QtWidgets.QAction(MainWindow)
        self.actionRun_VMD_contact_search.setObjectName("actionRun_VMD_contact_search")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionImport_Session = QtWidgets.QAction(MainWindow)
        self.actionImport_Session.setObjectName("actionImport_Session")
        self.actionExport_Session = QtWidgets.QAction(MainWindow)
        self.actionExport_Session.setObjectName("actionExport_Session")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionShow_Info = QtWidgets.QAction(MainWindow)
        self.actionShow_Info.setObjectName("actionShow_Info")
        self.actionExportData = QtWidgets.QAction(MainWindow)
        self.actionExportData.setCheckable(False)
        self.actionExportData.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionExportData.setObjectName("actionExportData")
        self.actionContact_Area_Calculations = QtWidgets.QAction(MainWindow)
        self.actionContact_Area_Calculations.setObjectName("actionContact_Area_Calculations")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionVMD_Remote_Control = QtWidgets.QAction(MainWindow)
        self.actionVMD_Remote_Control.setObjectName("actionVMD_Remote_Control")
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addAction(self.actionImport_Session)
        self.menuFile.addAction(self.actionExport_Session)
        self.menuFile.addAction(self.actionDefault)
        self.menuAbout.addAction(self.actionShow_Info)
        self.menuTools.addAction(self.actionExportData)
        self.menuTools.addAction(self.actionContact_Area_Calculations)
        self.menuTools.addAction(self.actionVMD_Remote_Control)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.lowerRangeField)
        MainWindow.setTabOrder(self.lowerRangeField, self.upperRangeField)
        MainWindow.setTabOrder(self.upperRangeField, self.filterRangeCheckbox)
        MainWindow.setTabOrder(self.filterRangeCheckbox, self.visModeButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.visModeButton.setText(_translate("MainWindow", "Vismode"))
        self.selection1label.setText(_translate("MainWindow", "-"))
        self.selection1.setText(_translate("MainWindow", "Selection 1:"))
        self.status.setText(_translate("MainWindow", "Status:"))
        self.selection2label.setText(_translate("MainWindow", "-"))
        self.statusLabel.setText(_translate("MainWindow", "-"))
        self.selection2.setText(_translate("MainWindow", "Selection 2:"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.zoomSliderLabel.setText(_translate("MainWindow", "Zoom:"))
        self.toLabel.setText(_translate("MainWindow", "to"))
        self.rangeLabel.setText(_translate("MainWindow", "Timeline range"))
        self.upperRangeField.setText(_translate("MainWindow", "end"))
        self.lowerRangeField.setText(_translate("MainWindow", "1"))
        self.filterRangeCheckbox.setText(_translate("MainWindow", "filter range"))
        self.statisticsButton.setText(_translate("MainWindow", "Statistics"))
        self.analysisButton.setText(_translate("MainWindow", "Accumulate Scores"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionRun_VMD_contact_search.setText(_translate("MainWindow", "Run VMD contact search"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Trajectory Data"))
        self.actionLoad_Data.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionImport_Session.setText(_translate("MainWindow", "Import Session"))
        self.actionImport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionExport_Session.setText(_translate("MainWindow", "Export Session"))
        self.actionExport_Session.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionDefault.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShow_Info.setText(_translate("MainWindow", "Developer Info"))
        self.actionExportData.setText(_translate("MainWindow", "Export Contact Data"))
        self.actionExportData.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionContact_Area_Calculations.setText(_translate("MainWindow", "Contact Area Calculation"))
        self.actionContact_Area_Calculations.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionVMD_Remote_Control.setText(_translate("MainWindow", "VMD Remote Control"))
        self.actionVMD_Remote_Control.setShortcut(_translate("MainWindow", "Ctrl+V"))

