# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Preferences.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesPanel(object):
    def setupUi(self, PreferencesPanel):
        PreferencesPanel.setObjectName("PreferencesPanel")
        PreferencesPanel.resize(443, 253)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreferencesPanel.sizePolicy().hasHeightForWidth())
        PreferencesPanel.setSizePolicy(sizePolicy)
        PreferencesPanel.setMinimumSize(QtCore.QSize(443, 253))
        PreferencesPanel.setMaximumSize(QtCore.QSize(443, 253))
        self.gridLayout = QtWidgets.QGridLayout(PreferencesPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.coreBox = QtWidgets.QSpinBox(PreferencesPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coreBox.sizePolicy().hasHeightForWidth())
        self.coreBox.setSizePolicy(sizePolicy)
        self.coreBox.setMinimum(1)
        self.coreBox.setMaximum(64)
        self.coreBox.setProperty("value", 4)
        self.coreBox.setObjectName("coreBox")
        self.gridLayout.addWidget(self.coreBox, 3, 1, 1, 1)
        self.applySettingsButton = QtWidgets.QPushButton(PreferencesPanel)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.gridLayout.addWidget(self.applySettingsButton, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(PreferencesPanel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.thresholdField = QtWidgets.QLineEdit(PreferencesPanel)
        self.thresholdField.setClearButtonEnabled(True)
        self.thresholdField.setObjectName("thresholdField")
        self.gridLayout.addWidget(self.thresholdField, 1, 1, 1, 1)
        self.nsPerFrameField = QtWidgets.QLineEdit(PreferencesPanel)
        self.nsPerFrameField.setClearButtonEnabled(True)
        self.nsPerFrameField.setObjectName("nsPerFrameField")
        self.gridLayout.addWidget(self.nsPerFrameField, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(PreferencesPanel)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(PreferencesPanel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(PreferencesPanel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.scoreFunctionField = QtWidgets.QLineEdit(PreferencesPanel)
        self.scoreFunctionField.setObjectName("scoreFunctionField")
        self.gridLayout.addWidget(self.scoreFunctionField, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(PreferencesPanel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)
        self.widget = QtWidgets.QWidget(PreferencesPanel)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.bbscScoreRadioButton = QtWidgets.QRadioButton(self.widget)
        self.bbscScoreRadioButton.setChecked(True)
        self.bbscScoreRadioButton.setObjectName("bbscScoreRadioButton")
        self.horizontalLayout.addWidget(self.bbscScoreRadioButton)
        self.customColorRadioButton = QtWidgets.QRadioButton(self.widget)
        self.customColorRadioButton.setObjectName("customColorRadioButton")
        self.horizontalLayout.addWidget(self.customColorRadioButton)
        self.pickColorButton = QtWidgets.QPushButton(self.widget)
        self.pickColorButton.setObjectName("pickColorButton")
        self.horizontalLayout.addWidget(self.pickColorButton)
        self.gridLayout.addWidget(self.widget, 5, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(PreferencesPanel)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 2)

        self.retranslateUi(PreferencesPanel)
        QtCore.QMetaObject.connectSlotsByName(PreferencesPanel)
        PreferencesPanel.setTabOrder(self.nsPerFrameField, self.thresholdField)
        PreferencesPanel.setTabOrder(self.thresholdField, self.scoreFunctionField)
        PreferencesPanel.setTabOrder(self.scoreFunctionField, self.coreBox)
        PreferencesPanel.setTabOrder(self.coreBox, self.bbscScoreRadioButton)
        PreferencesPanel.setTabOrder(self.bbscScoreRadioButton, self.customColorRadioButton)
        PreferencesPanel.setTabOrder(self.customColorRadioButton, self.pickColorButton)
        PreferencesPanel.setTabOrder(self.pickColorButton, self.applySettingsButton)

    def retranslateUi(self, PreferencesPanel):
        _translate = QtCore.QCoreApplication.translate
        PreferencesPanel.setWindowTitle(_translate("PreferencesPanel", "Preferences"))
        self.applySettingsButton.setText(_translate("PreferencesPanel", "Apply"))
        self.label.setText(_translate("PreferencesPanel", "Nanoseconds/frame:"))
        self.thresholdField.setText(_translate("PreferencesPanel", "0.0"))
        self.nsPerFrameField.setText(_translate("PreferencesPanel", "1.0"))
        self.label_4.setText(_translate("PreferencesPanel", "Cores:"))
        self.label_2.setText(_translate("PreferencesPanel", "Score Threshold:"))
        self.label_3.setText(_translate("PreferencesPanel", "Scoring Function: s(d)="))
        self.scoreFunctionField.setText(_translate("PreferencesPanel", "1.0 / (1.0 + np.exp(5.0 * (d - 4.0)))"))
        self.label_5.setText(_translate("PreferencesPanel", "Frame Colors:"))
        self.bbscScoreRadioButton.setText(_translate("PreferencesPanel", "bb/sc type"))
        self.customColorRadioButton.setText(_translate("PreferencesPanel", "custom"))
        self.pickColorButton.setText(_translate("PreferencesPanel", "Pick"))

