# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sasa.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SasaWidget(object):
    def setupUi(self, SasaWidget):
        SasaWidget.setObjectName("SasaWidget")
        SasaWidget.resize(712, 514)
        self.gridLayout_2 = QtWidgets.QGridLayout(SasaWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridWidget = QtWidgets.QWidget(SasaWidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridWidget1 = QtWidgets.QWidget(self.gridWidget)
        self.gridWidget1.setObjectName("gridWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphGridLayout = QtWidgets.QGridLayout()
        self.graphGridLayout.setObjectName("graphGridLayout")
        self.gridLayout_3.addLayout(self.graphGridLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gridWidget1, 7, 1, 1, 2)
        self.sasaSelection2TextField = QtWidgets.QLineEdit(self.gridWidget)
        self.sasaSelection2TextField.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sasaSelection2TextField.sizePolicy().hasHeightForWidth())
        self.sasaSelection2TextField.setSizePolicy(sizePolicy)
        self.sasaSelection2TextField.setMinimumSize(QtCore.QSize(0, 0))
        self.sasaSelection2TextField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sasaSelection2TextField.setObjectName("sasaSelection2TextField")
        self.gridLayout.addWidget(self.sasaSelection2TextField, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.sasaSelection1TextField = QtWidgets.QLineEdit(self.gridWidget)
        self.sasaSelection1TextField.setObjectName("sasaSelection1TextField")
        self.gridLayout.addWidget(self.sasaSelection1TextField, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        self.calcSasaButton = QtWidgets.QPushButton(self.gridWidget)
        self.calcSasaButton.setObjectName("calcSasaButton")
        self.gridLayout.addWidget(self.calcSasaButton, 8, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.gridWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadDataButton = QtWidgets.QPushButton(self.widget)
        self.loadDataButton.setObjectName("loadDataButton")
        self.verticalLayout.addWidget(self.loadDataButton)
        self.clearDataButton = QtWidgets.QPushButton(self.widget)
        self.clearDataButton.setObjectName("clearDataButton")
        self.verticalLayout.addWidget(self.clearDataButton)
        self.savePlotButton = QtWidgets.QPushButton(self.widget)
        self.savePlotButton.setObjectName("savePlotButton")
        self.verticalLayout.addWidget(self.savePlotButton)
        self.exportDataButton = QtWidgets.QPushButton(self.widget)
        self.exportDataButton.setObjectName("exportDataButton")
        self.verticalLayout.addWidget(self.exportDataButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.coreBox = QtWidgets.QSpinBox(self.widget)
        self.coreBox.setMinimum(1)
        self.coreBox.setMaximum(32)
        self.coreBox.setProperty("value", 4)
        self.coreBox.setObjectName("coreBox")
        self.verticalLayout.addWidget(self.coreBox)
        self.gridLayout.addWidget(self.widget, 7, 0, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(self.gridWidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sasaProgressBar = QtWidgets.QProgressBar(self.horizontalWidget)
        self.sasaProgressBar.setProperty("value", 0)
        self.sasaProgressBar.setTextVisible(True)
        self.sasaProgressBar.setInvertedAppearance(False)
        self.sasaProgressBar.setObjectName("sasaProgressBar")
        self.verticalLayout_2.addWidget(self.sasaProgressBar)
        self.gridLayout.addWidget(self.horizontalWidget, 8, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.calculateContactAreaCheckbox = QtWidgets.QCheckBox(self.gridWidget)
        self.calculateContactAreaCheckbox.setObjectName("calculateContactAreaCheckbox")
        self.gridLayout.addWidget(self.calculateContactAreaCheckbox, 5, 2, 1, 1)
        self.sasaRestrictionTextField = QtWidgets.QLineEdit(self.gridWidget)
        self.sasaRestrictionTextField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sasaRestrictionTextField.setObjectName("sasaRestrictionTextField")
        self.gridLayout.addWidget(self.sasaRestrictionTextField, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 1, 1, 2)
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 1)

        self.retranslateUi(SasaWidget)
        QtCore.QMetaObject.connectSlotsByName(SasaWidget)
        SasaWidget.setTabOrder(self.sasaSelection1TextField, self.sasaRestrictionTextField)
        SasaWidget.setTabOrder(self.sasaRestrictionTextField, self.sasaSelection2TextField)
        SasaWidget.setTabOrder(self.sasaSelection2TextField, self.calculateContactAreaCheckbox)
        SasaWidget.setTabOrder(self.calculateContactAreaCheckbox, self.coreBox)
        SasaWidget.setTabOrder(self.coreBox, self.loadDataButton)
        SasaWidget.setTabOrder(self.loadDataButton, self.savePlotButton)
        SasaWidget.setTabOrder(self.savePlotButton, self.exportDataButton)
        SasaWidget.setTabOrder(self.exportDataButton, self.calcSasaButton)

    def retranslateUi(self, SasaWidget):
        _translate = QtCore.QCoreApplication.translate
        SasaWidget.setWindowTitle(_translate("SasaWidget", "Surface Areas"))
        self.label_2.setText(_translate("SasaWidget", "Restriction:"))
        self.calcSasaButton.setText(_translate("SasaWidget", "Calculate"))
        self.loadDataButton.setText(_translate("SasaWidget", "Load Data"))
        self.clearDataButton.setText(_translate("SasaWidget", "Clear Data"))
        self.savePlotButton.setText(_translate("SasaWidget", "Save Plot"))
        self.exportDataButton.setText(_translate("SasaWidget", "Export Data"))
        self.label_4.setText(_translate("SasaWidget", "Cores:"))
        self.label.setText(_translate("SasaWidget", "Selection:"))
        self.calculateContactAreaCheckbox.setText(_translate("SasaWidget", "contact"))
        self.label_3.setText(_translate("SasaWidget", "Selection 2:"))

